import Header from '@/components/layout/Header'
import './globals.css'
import localFont from "next/font/local"

const yekanFont = localFont({
  src:'./font/Yekan.woff2',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={yekanFont.className}>
      <Header/>
        {children}</body>
    </html>
  )
}
