import Header from "@/components/layout/Header";
import "./globals.css";
import localFont from "next/font/local";
import Head from "next/head";
import Provider from "@/components/auth/Provider";
import { getServerSession } from "next-auth";
import { getSession } from "next-auth/react";
import { authOptions } from "./api/auth/[...nextauth]/route";



const yekanFont = localFont({
  src: "./font/Yekan.woff2",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={yekanFont.className}>
        <Provider>
          <Header session={session} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
